/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ir_moke_jsysbox_file_JFile */

#ifndef _Included_ir_moke_jsysbox_file_JFile
#define _Included_ir_moke_jsysbox_file_JFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ir_moke_jsysbox_file_JFile
 * Method:    mime
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ir_moke_jsysbox_file_JFile_mime
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
