/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ir_moke_jsysbox_firewall_JFirewall */

#ifndef _Included_ir_moke_jsysbox_firewall_JFirewall
#define _Included_ir_moke_jsysbox_firewall_JFirewall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ir_moke_jsysbox_firewall_JFirewall
 * Method:    restore
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ir_moke_jsysbox_firewall_JFirewall_restore
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ir_moke_jsysbox_firewall_JFirewall
 * Method:    export
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ir_moke_jsysbox_firewall_JFirewall_export
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
