/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ir_moke_jsysbox_system_JPartition */

#ifndef _Included_ir_moke_jsysbox_system_JPartition
#define _Included_ir_moke_jsysbox_system_JPartition
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     ir_moke_jsysbox_system_JPartition
 * Method:    mount
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ir_moke_jsysbox_system_JPartition_mount
  (JNIEnv *, jclass, jstring, jstring, jstring, jint, jstring);

/*
 * Class:     ir_moke_jsysbox_system_JPartition
 * Method:    umount
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ir_moke_jsysbox_system_JPartition_umount
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ir_moke_jsysbox_system_JPartition
 * Method:    getFilesystemStatistics
 * Signature: (Ljava/lang/String;)Lir/moke/jsysbox/system/HDDPartition;
 * */
JNIEXPORT jobject JNICALL Java_ir_moke_jsysbox_system_JPartition_getFilesystemStatistics
    (JNIEnv *, jclass, jstring);

/*
 * Class:     ir_moke_jsysbox_system_JPartition
 * Method:    getFilesystemStatistics
 * Signature: (Ljava/lang/String;)Z
 * */
JNIEXPORT void JNICALL Java_ir_moke_jsysbox_system_JPartition_swapOn
    (JNIEnv *, jclass, jstring);

/*
 * Class:     ir_moke_jsysbox_system_JPartition
 * Method:    getFilesystemStatistics
 * Signature: (Ljava/lang/String;)Z
 * */
JNIEXPORT void JNICALL Java_ir_moke_jsysbox_system_JPartition_swapOff
    (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
